language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
 - git submodule update --init --recursive
 - git clone https://github.com/mrtrizer/FlappyTools.git flappytools
 - pushd flappytools
 - cmake -G "Unix Makefiles"
 - sudo make install
 - popd
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base libglew-dev mesa-common-dev freeglut3-dev

script:
#opengl test project
 - pushd tests_gl
 - flappy prebuild qt
 - pushd targets/qt
 - qmake tests_gl.pro
 - make
 - popd
 - popd
#core tests
 - cd tests_core
 - flappy prebuild qt
 - cd targets/qt
 - qmake tests_core.pro
 - make
 - ./tests_core

after_success:
  - bash <(curl -s https://codecov.io/bash)
