language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
 - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install libsdl2-dev libsdl2-image-dev
 - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
 - sudo apt-get install -qq gcc-6 g++-6 nodejs
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
 - git submodule update --init --recursive
 - git clone https://github.com/mrtrizer/FlappyTools2.git flappytools
 - pushd flappytools
 - cmake -G "Unix Makefiles"
 - sudo make install
 - popd
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base libglew-dev mesa-common-dev freeglut3-dev libxi-dev
 - git clone https://github.com/KhronosGroup/glslang.git
 - pushd glslang
 - git clone https://github.com/google/googletest.git External/googletest
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
 - sudo make install
 - popd
 - git clone https://github.com/KhronosGroup/SPIRV-Cross.git
 - pushd SPIRV-Cross
 - make
 - sudo ln -s `pwd`/spirv-cross /usr/local/bin/spirv-cross
 - popd

script:
# Test of shader compilation to SPIR-V
 - pushd modules/Gl/res_src_330
 - glslangValidator -V -H -S vert -o shape_shader_vert.spv shape_shader.vglsl --aml
 - spirv-cross ./shape_shader_vert.spv --es
 - spirv-cross ./shape_shader_vert.spv --hlsl
 - glslangValidator -V -H -S frag -o shape_shader_frag.spv shape_shader.fglsl --aml
 - spirv-cross ./shape_shader_frag.spv --es
 - spirv-cross ./shape_shader_frag.spv --hlsl
 - glslangValidator -V -H -S vert -o texture_shader_vert.spv texture_shader.vglsl --aml
 - spirv-cross ./texture_shader_vert.spv --es
 - spirv-cross ./texture_shader_vert.spv --hlsl
 - glslangValidator -V -H -S frag -o texture_shader_frag.spv texture_shader.fglsl --aml
 - spirv-cross ./texture_shader_frag.spv --es
 - spirv-cross ./texture_shader_frag.spv --hlsl
 - popd

#Core tests
 - pushd modules/Core/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_Core
 - popd
 - popd

#Std test project (build only)
 - pushd modules/Std/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_Std
 - popd
 - popd

#ResManager test project (build only)
 - pushd modules/ResManager/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_ResManager
 - popd
 - popd

#Tools test project (build only)
 - pushd modules/Tools/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_Tools
 - popd
 - popd

#EventBus test project (build only)
 - pushd modules/EventBus/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_EventBus
 - popd
 - popd

#CoreComponents test project (build only)
 - pushd modules/CoreComponents/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_CoreComponents
 - popd
 - popd

#CoreResources test project (build only)
 - pushd modules/CoreResources/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_CoreResources
 - popd
 - popd

#JsonRes test project (build only)
 - pushd modules/JsonRes/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_JsonRes
 - popd
 - popd

#Sdl2Manager test project (build only)
 - pushd modules/Sdl2Manager/tests
 - flappy build cmake
 - popd

after_success:
  - bash <(curl -s https://codecov.io/bash)
