language: cpp
compiler: gcc
sudo: required
dist: trusty

env:
  global:
    - CODECOV_TOKEN=:32cab459-0975-4208-a94c-cb3be426159b

before_install:
 - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:pinepain/libv8-archived -y
 - sudo add-apt-repository ppa:jonathonf/llvm -y
 - sudo apt-get update -qq
 - sudo apt-get install libsdl2-dev libsdl2-image-dev
 - sudo apt-get install libvorbis-dev libopenal-dev
 - sudo apt-get install libv8-5.2-dev
 - sudo apt-get install llvm-5.0-dev
 - sudo apt-get install clang-5.0-dev
 - sudo apt-get install ninja-build
 - sudo apt-get install -y ccache
 - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
 - sudo apt-get install -qq gcc-6 g++-6 nodejs
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
 - git submodule update --init --recursive
 - git clone https://github.com/mrtrizer/FlappyTools2.git flappytools
 - pushd flappytools
 - cmake -G "Unix Makefiles"
 - sudo make install
 - popd
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base libglew-dev mesa-common-dev freeglut3-dev libxi-dev
 - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential
 - git clone https://github.com/KhronosGroup/glslang.git
 - pushd glslang
 - git clone https://github.com/google/googletest.git External/googletest
 - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
 - sudo make install
 - popd
 - git clone https://github.com/KhronosGroup/SPIRV-Cross.git
 - pushd SPIRV-Cross
 - make
 - sudo ln -s `pwd`/spirv-cross /usr/local/bin/spirv-cross
 - popd
 - export CXX="ccache g++ -coverage -O0"

script:

#V8JSEngine tests
 - pushd modules/V8JSEngine/tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests_V8JSEngine
 - popd
 - popd

# Test of shader compilation to SPIR-V
 - pushd modules/Gl/res_src_330
 - glslangValidator -V -H -S vert -o shape_shader_vert.spv shape_shader.vglsl --aml
 - spirv-cross ./shape_shader_vert.spv --es
 - spirv-cross ./shape_shader_vert.spv --hlsl
 - glslangValidator -V -H -S frag -o shape_shader_frag.spv shape_shader.fglsl --aml
 - spirv-cross ./shape_shader_frag.spv --es
 - spirv-cross ./shape_shader_frag.spv --hlsl
 - glslangValidator -V -H -S vert -o texture_shader_vert.spv texture_shader.vglsl --aml
 - spirv-cross ./texture_shader_vert.spv --es
 - spirv-cross ./texture_shader_vert.spv --hlsl
 - glslangValidator -V -H -S frag -o texture_shader_frag.spv texture_shader.fglsl --aml
 - spirv-cross ./texture_shader_frag.spv --es
 - spirv-cross ./texture_shader_frag.spv --hlsl
 - popd

#Unit tests
 - pushd tests
 - flappy build cmake
 - pushd generated/cmake/build
 - ./tests
 - popd
 - popd

#OggAudioRes build
 - pushd modules/OggAudioRes/demo
 - flappy build cmake
 - popd

#Sdl2Manager build
 - pushd modules/Sdl2Manager/demo
 - flappy build cmake
 - popd

#Box2DManager tests
 - pushd modules/Box2DManager/demo
 - flappy build cmake
 - popd

#DebugDraw tests
 - pushd modules/DebugDraw/demo
 - flappy build cmake
 - popd

after_success:
  - bash <(curl -s https://codecov.io/bash)
