language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install libsdl2-dev libsdl2-image-dev
 - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
 - sudo apt-get install -qq gcc-5 g++-5 nodejs
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
 - git submodule update --init --recursive
 - git clone https://github.com/mrtrizer/FlappyTools2.git flappytools
 - pushd flappytools
 - cmake -G "Unix Makefiles"
 - sudo make install
 - popd
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base libglew-dev mesa-common-dev freeglut3-dev libxi-dev

script:
#Core tests
 - pushd modules/Core/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_Core
 - popd

#Std test project (build only)
 - pushd modules/Std/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_Std
 - popd

#ResManager test project (build only)
 - pushd modules/ResManager/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_ResManager
 - popd

#Tools test project (build only)
 - pushd modules/Tools/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_Tools
 - popd

#EventBus test project (build only)
 - pushd modules/EventBus/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_EventBus
 - popd

#CoreComponents test project (build only)
 - pushd modules/CoreComponents/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_CoreComponents
 - popd

#CoreResources test project (build only)
 - pushd modules/CoreResources/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_CoreResources
 - popd

#JsonRes test project (build only)
 - pushd modules/JsonRes/tests
 - flappy build cmake
 - ./generated/cmake/build/tests_JsonRes
 - popd

#Sdl2Manager test project (build only)
 - pushd modules/Sdl2Manager/tests
 - flappy build cmake
 - popd

after_success:
  - bash <(curl -s https://codecov.io/bash)
