language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq gcc-5 g++-5
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
 - git submodule update --init --recursive
 - git clone https://github.com/mrtrizer/FlappyTools.git flappytools
 - pushd flappytools
 - cmake -G "Unix Makefiles"
 - sudo make install
 - popd
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base libglew-dev mesa-common-dev freeglut3-dev

script:
#opengl test project
 - pushd targets/qt.tests
 - flappy prebuild qt.tests
 - qmake tests_gl_tests.pro
 - make
 - ./tests_gl_tests
 - popd

after_success:
  - bash <(curl -s https://codecov.io/bash)
