#!/usr/bin/python
import os
import sys
import shutil
import tools

engineDir = os.path.dirname(os.path.realpath(sys.argv[0]))
engineResDir = os.path.join(engineDir, "res")
templateConfigDir = os.path.join(engineDir, "templates/config/")
outResDir = "build/res/"
outSrcDir = "build/src/"

if not os.path.exists(outResDir):
    os.makedirs(outResDir)

if not os.path.exists(outSrcDir):
    os.makedirs(outSrcDir)

resDirs = [engineResDir, "res/"]

print "Resource processing..."
for resDir in resDirs:
    tools.copyAll(resDir, outResDir)

print "Config generation..."
config = {"revision": os.popen("git describe --always").read().strip()}
tools.replaceAll(templateConfigDir, outSrcDir, config)
