#!/usr/bin/python
import os
import sys
import json

import tools

if (len(sys.argv) < 2):
    print(
        "FlappyEngine resource copy tool.\n"
        "Script copies resources from build/res for target platform.\n\n"
        "Use format:\n"
        " copyres <platform> [project path]\n\n"
        "For example:\n"
        " copyres cmake\n"
        "or if you are not in a project root\n"
        " cd projects/cmake\n"
        " copyres cmake ../../\n")
    exit(1)

targetDir = os.path.join(".", "projects", sys.argv[1], "res")
resDir = "./build/res"

print "Resource copy to target..."
