#!/usr/bin/python
import os
import sys
import json

import tools

if (len(sys.argv) < 2):
    print tools.printHelp(sys.argv[0], "gentarget")
    exit(1)
engineDir = os.path.dirname(os.path.realpath(sys.argv[0]))
templateDir = os.path.join(engineDir, "templates/targets", sys.argv[1])
if (not os.path.isdir(templateDir)):
    print("Target is not supported: " + sys.argv[1])
    exit(2)
projectDir = os.path.realpath(os.path.join("projects", sys.argv[1]))
configPath = os.path.realpath("config.json")

print("Template: " + templateDir)
print("Target: " + projectDir)
print("Config: " + configPath)

jsonFile = open(configPath, 'r')
config = json.load(jsonFile)

tools.replaceAll(templateDir, projectDir, config)
